env:
  es6: true
  browser: true

extends:
  - "eslint:recommended"

parserOptions:
  ecmaVersion: 6
  sourceType: module

overrides:
  - files:
      "**/*.test.js"
    env:
      jest: true
    extends:
      - "plugin:jest/recommended"
      - "plugin:jest/style"
    plugins:
      - jest
