env:
  es6: true
  browser: true

parser: '@typescript-eslint/parser'

extends:
  - "eslint:recommended"
  - "plugin:promise/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'

plugins:
  - "promise"
  - "import"
  - '@typescript-eslint'

parserOptions:
  ecmaVersion: 6
  sourceType: module
  tsconfigRootDir: '.'
  project: ['./tsconfig.json']

overrides:
  - files:
      "**/*.test.js"
    env:
      jest: true
    extends:
      - "plugin:jest/recommended"
      - "plugin:jest/style"
    plugins:
      - jest
