env:
  es6: true
  browser: true

parser: '@typescript-eslint/parser'

extends:
  - "eslint:recommended"
  - "plugin:promise/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"

plugins:
  - "promise"
  - "import"

rules:
  promise/always-return: ["warn"]
  promise/catch-or-return: ["warn"]
  promise/no-return-wrap: ["warn"]

parserOptions:
  ecmaVersion: 6
  sourceType: module

overrides:
  - files:
      - "src/**/*.js"
      - "src/**/*.ts"
    extends:
      - "plugin:import/typescript"
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    parserOptions:
      tsconfigRootDir: '.'
      project: ['./tsconfig.json']
    plugins:
      - '@typescript-eslint'
    rules:
      no-var: ["warn"]
      no-undef: ["warn"]
      prefer-rest-params: ["warn"]
      prefer-const: ["warn"]
      "@typescript-eslint/camelcase": ["warn"]
      "@typescript-eslint/no-use-before-define": ["warn"]
      "@typescript-eslint/no-this-alias": ["warn"]
      "@typescript-eslint/prefer-string-starts-ends-with": ["warn"]
      "@typescript-eslint/prefer-includes": ["warn"]
  - files:
      "tests/**/*.js"
    env:
      jest: true
    extends:
      - "plugin:jest/recommended"
      - "plugin:jest/style"
    plugins:
      - jest
