env:
  es6: true
  browser: true

parser: '@typescript-eslint/parser'

extends:
  - "eslint:recommended"
  - "plugin:promise/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"

plugins:
  - "promise"
  - "import"

parserOptions:
  ecmaVersion: 6
  sourceType: module

overrides:
  - files:
      - "src/**/*.js"
      - "src/**/*.ts"
    extends:
      - "plugin:import/typescript"
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    parserOptions:
      tsconfigRootDir: '.'
      project: ['./tsconfig.json']
    plugins:
      - '@typescript-eslint'
  - files:
      "tests/**/*.js"
    env:
      jest: true
    extends:
      - "plugin:jest/recommended"
      - "plugin:jest/style"
    plugins:
      - jest
