trigger:
  batch: true
  branches:
    include:
    - master
    - release-*
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

jobs:
  - job: main_build
    displayName: 'Main Build'

    dependsOn: lint
    condition: succeeded()

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      displayName: 'Install Node'
      inputs:
        versionSpec: '10.x'

    - task: Cache@2
      displayName: 'Check Cache'
      inputs:
        key: 'yarn | yarn.lock'
        path: 'node_modules'
        cacheHitVar: CACHE_RESTORED

    - script: 'yarn install --frozen-lockfile'
      displayName: 'Install Dependencies'
      condition: ne(variables.CACHE_RESTORED, 'true')

    - script: 'yarn build'
      displayName: 'Build'

    - script: 'test -d dist'
      displayName: 'Check Build'

    - script: 'yarn pack --filename jellyfin-apiclient-javascript.tgz'
      displayName: 'Bundle Release'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Release'
      condition: succeeded()
      inputs:
        targetPath: '$(Build.SourcesDirectory)/jellyfin-apiclient-javascript.tgz'
        artifactName: 'jellyfin-apiclient-javascript'

  - job: lint
    displayName: 'Lint'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      displayName: 'Install Node'
      inputs:
        versionSpec: '10.x'

    - task: Cache@2
      displayName: 'Check Cache'
      inputs:
        key: 'yarn | yarn.lock'
        path: 'node_modules'
        cacheHitVar: CACHE_RESTORED

    - script: 'yarn install --frozen-lockfile'
      displayName: 'Install Dependencies'
      condition: ne(variables.CACHE_RESTORED, 'true')

    - script: 'yarn run lint'
      displayName: 'Run ESLint'
  - job: test
    displayName: 'Tests'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      displayName: 'Install Node'
      inputs:
        versionSpec: '10.x'

    - task: Cache@2
      displayName: 'Check Cache'
      inputs:
        key: 'yarn | yarn.lock'
        path: 'node_modules'
        cacheHitVar: CACHE_RESTORED

    - script: 'yarn install --frozen-lockfile'
      displayName: 'Install Dependencies'
      condition: ne(variables.CACHE_RESTORED, 'true')

    - script: 'yarn run jest --ci --reporters=default --reporters=jest-junit --coverage'
      displayName: 'Run Jest'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunner: JUnit
        testResultsFiles: 'junit.xml'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'



